[package]
name = "rsomics-bamio"
version = "0.4.0"
description = "Validated alignment records and indexed or parallel I/O for rsomics products"
edition = "2024"
rust-version = "1.91"
license = "MIT OR Apache-2.0"
repository = "https://github.com/omics-rust/rsomics-bamio"
homepage = "https://github.com/omics-rust/rsomics-bamio"
documentation = "https://docs.rs/rsomics-bamio"
authors = ["Zane Leong <efd@live.com>"]
readme = "README.md"
categories = ["science"]
keywords = ["bam", "bgzf", "bioinformatics", "samtools", "reader"]

[dependencies]
rsomics-common = { version = "0.10" }
noodles = { version = "0.110", features = ["sam", "bam", "bgzf", "core", "cram", "csi", "fasta"] }
noodles-bgzf = { version = "0.47", features = ["libdeflate"] }
noodles-util = { version = "0.79", features = ["alignment"] }
crossbeam-channel = "0.5"
libdeflater = "1"

[dev-dependencies]
tempfile = "3"
